# Generated by Django 3.1 on 2020-08-27 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charityapp', '0001_initial'),
        ('ngo', '0003_madedonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='madedonation',
            name='ngo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='charityapp.ngo'),
        ),
    ]
